---
# Determines if the required dependencies are installed

- name: Install Debian deps
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{debian_deps}}"
  when: ansible_distribution == 'Debian'
  become: true

- name: Install Ubuntu deps
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{ubuntu_deps}}"
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Install Fedora deps
  dnf:
    name: "{{item}}"
    state: present
  with_items: "{{fedora_deps}}"
  when: ansible_distribution == 'Fedora'
  become: true

- name: Install CentOS/RHEL deps
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{centos_deps}}"
  when: ansible_distribution == 'Red Hat Enterprise Linux'
  become: true

- name: Install Archlinux Deps
  pacman:
    name: "{{item}}"
    state: present
  with_items: "{{arch_deps}}"
  when: ansible_distribution == 'Archlinux'
  become: true

- name: Download rust setup script
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y "

- name: Set rust default to nightly
  shell: "{{ansible_env.HOME}}/.cargo/bin/rustup default nightly"
